### ISSUE TITLE
Consumo excessivo de CPU quando pinpad fica muito tempo idle

### ISSUE THREAD

**Issue by ronflima** [stone-payments/sdk-ios-v2#10]
Este é um problema recorrente no pinpad Gertec Mobi Pin 10. Porém, há um fato novo que pode auxiliar a tornar o driver mais robusto para as falhas de comunicação.

Quando o pinpad fica muito tempo idle ele deve desligar, incorretamente, a comunicação bluetooth com o smartphone, tornando-se insensível a estímulos. Observou-se, no entanto, que uma tentativa de escrita do driver Stone, quando ocorre esta falha de comunicação, resulta no recebimento de um sinal SIGPIPE. Uma sugestão é criar um handle para este sinal via _sigaction_ (ver sigaction.h) e forçar o retorno de um status de erro ao cliente do driver. 

Vale a pena verificar se os inputStream/outputStream do EASession falham em operações de I/O.

**Comment by filpgame** [comment]
Corrigido na [v2.4.0](https://github.com/stone-payments/sdk-ios-v2/releases/tag/2.4.0)
