### ISSUE TITLE
Signal SIGPIPE

### ISSUE THREAD

**Issue by gusmelki** [stone-payments/sdk-ios-v2#11]
Quando a conexão com o pinpad via bluetooth é perdida, tanto o método de conexão com o pinpad "STNPinPadConnectionProvider.connect", quanto o método para checar a conexão "validatePinpadConnection()", retornam um sinal SIGPIPE, quebrando a aplicação.

Obs: O pinpad é da PAX modelo D180.

Acredito que esse problema tem relação com o issue já aberto -> [Issue #10](https://github.com/stone-pagamentos/sdk-ios-v2/issues/10)

**Comment by jaisonv** [comment]
Oi, Gustavo.

Nós não damos suporte a esse dispositivo. Você consegue parear com ele no iOS e executar as operações do nosso SDK?

Sobre o erro de quando perde a conexão, eu estou adicionando uma correção. Pode baixar na página de releases e fazer um teste?

**Comment by CharlesNascimento** [comment]
Olá, também estou tendo problemas de conexão perdida com a PAX D180. Estou usando a versão mais recente do SDK, mesmo assim as falhas persistem. Consigo fazer transações normalmente com este modelo, único problema são essas perdas de conexão aleatórias, em momentos aleatórios da operação. Mesma coisa com a MOBI PIN10, mesmo executando o "STNPinPadConnectionProvider.connect" antes da transação, o pinpad pode parar de responder durante a operação.

Estou fazendo os testes em um iPhone 5C com o iOS 10.3.1 e utilizando o Xcode 8.2.1.

**Comment by jaisonv** [comment]
Charles,

Esse problema já é conhecido no MOBI PIN. Não sabia que também ocorria em outros dispositivos. Sugiro tentar a mesma forma de contornar que usamos para o MOBI PIN. Se ele ficar inativo por mais de 3 minutos isso sempre irá ocorrer. [Nessa parte da documentação](https://github.com/stone-pagamentos/sdk-ios-v2/tree/master/objc#criação-de-sessão-com-o-pinpad) nós explicamos que para contornar isso pode enviado algo para o display do pinpad antes de deixá-lo ficar inativo. Tente com esse que você está usando da PAX e me diga se resolve o problema.

Lembrando que isso não é um problema da plataforma, pois isso também ocorre no dispositivo. Esse problema é do pinpad.

Aguardo seu feedback.

**Comment by CharlesNascimento** [comment]
Olá, Jaison.

Fiz essa tentativa de a cada 3 minutos mandar uma mensagem para o pinpad, deu uma melhorada na quantidade de perdas de conexão, porém ainda acontecem. Inclusive, agora há pouco uma transação foi aprovada, e antes de retirar o cartão do pinpad, a conexão foi perdida, ou seja, a transação não foi salva localmente pela stone, me impedindo de fazer algum pós-processamento. Fiz os testes com ambos os pinpads. Outros problemas que identifiquei foram:

Em ambos pinpads, caso o cartão seja removido na tela de senha, a operação não é cancelada. E com alguns cartões, a conexão é perdida instantaneamente.

Na D180, quando a transação expira na tela de senha, a conexão é perdida (Problema identificado também no Android).

Outra coisa estranha é que recentemente, um cartão ELO que uso aqui para testes começou a ser aprovado pela Stone. E o Hipercard está pedindo senha, não sei se é aprovado, pois não tenho como finalizar a transação.

**Comment by jaisonv** [comment]
Charles,

Caso 3 minutos não seja suficiente, você pode tentar com 2. Se ainda assim não resolver, nós não temos muito o que fazer.

Sobre a remoção do cartão, eu já identifiquei o erro. Vou corrigir e subir uma nova versão com essa correção em breve.

No caso do timeout no D180, eu fiz um teste e ele não dá timeout. Deixei ele na minha mesa por 5 minutos com o cartão inserido e ao remover o cartão ele voltou para o app normalmente.

Sobre as bandeiras, nós somente damos suporte a Master e Visa. Estamos trabalhando para dar suporte a Elo, Alelo e Ticket em breve.

**Comment by CharlesNascimento** [comment]
Jaison,

1. Já baixei pra casa de segundos, mas não mudou nada. Na verdade meu maior problema não são perdas de conexão antes de iniciar a operação, mas sim durante. Vou dar alguns exemplos: 

- Quando eu insiro o cartão, o pinpad mostra a mensagem: "Selecionado: Débito", e deveria ir pra tela de senha, mas não vai. Continua nessa tela eternamente. -> ( https://ibb.co/nC2pGQ ; https://ibb.co/d6j3bQ)

- Quando passo um cartão pela tarja, a tela do pinpad fica toda branca e não recebo nenhuma resposta. -> ( https://ibb.co/ggqbwQ ; https://ibb.co/hta9GQ )

- Quando digito a senha do cartão e pressiono "Entra", a tela do pinpad fica toda branca e não recebo nenhuma resposta. -> ( https://ibb.co/nd09GQ ; https://ibb.co/ffZrVk ; https://ibb.co/mkmibQ ; https://ibb.co/ckQbwQ )

- Quando uma transação é aprovada ou negada, o pinpad pede para retirar o cartão, retiro ele, mas o pinpad aparentemente não identifica que foi retirado e fica travado eternamente, o que me impede de fazer algum pós-processamento. -> ( https://ibb.co/mKedbQ )

Lembrando que esses problemas não acontecem sempre, mas sim esporadicamente. Porém não deveriam acontecer nunca. Talvez "Perda de conexão" não seja o termo correto para esses casos, mas sim erros de processamento no lado da aplicação, não tenho certeza.

2. Que bom que já identificou o problema, fico no aguardo da nova versão.

3. Fiz alguns testes com outra D180 que temos aqui, e realmente não aconteceu timeout. Aparentemente é alguma particularidade da outra D180, já estamos investigando isso.

4. Foi justamente esse o problema, ELO não deveria ser aprovado, mas fiz várias transações com ele semana passada que foram aprovadas, tenho todos os códigos de aprovação aqui. Mas parece que isso voltou ao normal, pois tentei várias vezes sexta-feira e ontem, mas todas foram devidamente negadas.

**Comment by jaisonv** [comment]
Charles,

Muito obrigado por reportar.

1 - Nós vamos investigar esse problema.

2 - Já está programado para sair na próxima versão.

3 - Realmente, as vezes acontece com alguns pinpads. Alguns fabricantes tomam mais cuidado com uns modelos do que com outros.

4 - Nesse caso não estamos com isso feito na SDK. Na versão em que estamos trabalhando agora começamos a implementar ELO. Mas se foi aprovado antes pode ter ocorrido alguma falha por parte da API, a qual não temos controle do nosso lado.

**Comment by CharlesNascimento** [comment]
Ok, Jaison. Agradeço e fico no aguardo.

**Comment by filpgame** [comment]
Corrigido na [v2.4.0](https://github.com/stone-payments/sdk-ios-v2/releases/tag/2.4.0) Caso continue ocorrendo, por favor reabra a issue
