### ISSUE TITLE
Pinpads não-BLE falhando demais

### ISSUE THREAD

**Issue by CharlesNascimento** [stone-payments/sdk-ios-v2#14]
Boa tarde. Já implementei o suporte aos pinpads BLE na minha aplicação, e tem funcionado muito bem. Porém, os pinpads não-BLE continuam funcionando muito mal, como já tinha relatado na issue #11 alguns meses atrás. Praticamente todos os problemas que relatei lá ainda persistem: Maquininha não segue para a próxima tela; A tela da maquininha fica toda em branco; Transação nem inicia. E o pior é que quando algum destes erros acontece, o callback da transação nunca é chamado, o que deixa minha aplicação aguardando eternamente. Utilizei tanto uma MOBI PIN 10 quanto uma PAX-D180 para os testes. Consigo reproduzir estes problemas facilmente na aplicação Demo da Stone, inclusive vou enviar algumas fotos. Também vou enviar alguns stack traces que o Firebase Crash Reporting capturou e talvez possam ajudar a identificar os possíveis problemas. Fico no aguardo.

Fotos das falhas:

[Travado em SELECIONADO: Debito](https://ibb.co/e6rLAG)
[Transação não inicia](https://ibb.co/ed5fAG)
[Transação finalizada, mas callback não é chamado](https://ibb.co/ipwbjb)
[Travado antes da tela de senha](https://ibb.co/dibyxw)

Stack traces:

[Stack trace 1](https://pastebin.com/mYub48xM)
[Stack trace 2](https://pastebin.com/FFkeGcdm)
[Stack trace 3](https://pastebin.com/EfyvSMz6)
[Stack trace 4](https://pastebin.com/W7rDpMP3)

**Comment by filpgame** [comment]
Boa tarde Charles
Muito obrigado pelo feedback e pelas informações!
Este é um problema conhecido da SDK e recentemente colocamos este problema como prioridade. Pode nos dizer como você reproduz este erro?
Mais uma vez obrigado pelas infos!

**Comment by CharlesNascimento** [comment]
Olá, filpgame. Na verdade não existe uma receita exata para que estes problemas aconteçam. Eu simplesmente vou fazendo transações aleatórias até que algum erro acontece, às vezes acontece de primeira, às vezes demora um pouco mais, porém tem acontecido bastante. Que bom que colocaram como prioridade, gostaria muito que isso fosse corrigido o quanto antes.

**Comment by filpgame** [comment]
Corrigido na [v2.4.0](https://github.com/stone-payments/sdk-ios-v2/releases/tag/2.4.0)
