### ISSUE TITLE
Simulador

### ISSUE THREAD

**Issue by gusmelki** [stone-payments/sdk-ios-v2#8]
Olá Galera, tudo bom?

Não é possível fazer o build do app no simulador com a nova versão do sdk de vocês, correto?

Abs!

**Comment by jaisonv** [comment]
Gustavo, Nós tiramos isso pois estava dando problemas na hora de subir o aplicativo para Appstore. Como não é possivel rodar as operações via bluetooth com pelo simulador, não vimos problema em remover. Caso esteja tentar rodar testes, nós recomendamos tirar o SDK do target de testes.
